### ISSUE TITLE
Error on dev and build

### ISSUE THREAD

**Issue by PMLS3** [HuakunShen/tauri-nuxt-template#1]
thank you for the project... 

after project creation if I run pnpm dev or pnpm build I get the following error:

tauri "dev"

       Error failed to get cargo metadata: No such file or directory (os error 2)
 ELIFECYCLE  Command failed with exit code 1.
 
 Can you please assist?

**Comment by HuakunShen** [comment]
What are the commands you used? By default this project was set up with `npm` rather than `pnpm`, but `pnpm` should work. I had no issue running this project.

```bash
# clone the project first
pnpm i

pnpm tauri dev
```

You should use `pnpm tauri dev` command not `pnpm dev`, and please make sure your rust is set up properly. 
If you can run an official tauri template you should be able to run this one.

**Comment by PMLS3** [comment]
Hi @HuakunShen , sorry I found a solution. I have to run the following two commands every-time before build.

source "$HOME/.cargo/env"
rustup update
